In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("youtube_videos.csv")

In [4]:
df.head(10)

,video_id,title,description,published_at,viewCount,likeCount,commentCount,duration
0,UigGPZYdyoo,Just LEARN THESE 6 courses to Make Money Onlin...,"In this video, I break down how you can shift ...",2025-12-04 10:30:31+00:00,1831,120,15,603
1,n5Ev-klyqXc,My journey ❤️🤍 I just felt like sharing 🫠❤️ #...,"Don't forget to like, comment, and subscribe f...",2025-12-02 10:30:40+00:00,6310,588,20,78
2,fR-2AiAxDhk,"POV: I Made ₹2,687 in 60- Minutes from the Eas...","POV: I Made ₹2,687 in 1 hour from the Easiest ...",2025-11-27 10:30:27+00:00,5897,265,47,481
3,Ze1t4p0QCT0,"You know that phase when life says 'Bas, ho gy...","Don't forget to like, comment, and subscribe f...",2025-11-25 10:30:32+00:00,8944,666,4,61
4,Tr6Z8guOdM4,Complete Beginners Guide To Affinity Pixel Stu...,Complete Beginners Guide To Affinity Pixel Stu...,2025-11-20 10:30:31+00:00,2257,94,30,2140
5,0eIDN3uZiCg,I’m super excited for this new journey. I hope...,"Time for a cool introduction, right?\nWill the...",2025-11-18 10:30:01+00:00,15161,812,11,43
6,fbd903qIEns,7 Lessons for my Younger Self! (Watch this if ...,7 Things I wish I knew BEFORE 2025 started (My...,2025-11-13 10:30:25+00:00,3682,250,61,1152
7,fPpBv7UGHT4,"My story of comeback 💖 Reset, recharge but don...","Don't forget to like, comment, and subscribe f...",2025-11-11 10:30:24+00:00,10638,560,10,55
8,stegnhfnk6s,Complete Beginners Guide To 2025 🔥 Full Affin...,Complete Beginners Guide To 2025 🔥 Full Canva...,2025-11-06 10:30:43+00:00,31472,1155,123,1755
9,mcbAB1mNU7c,Design Your Portfolio on Behance in 30 Minutes...,Want to build a professional Behance portfolio...,2025-10-30 10:30:38+00:00,7322,306,42,1795

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491 entries, 0 to 490
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   video_id      491 non-null    object
 1   title         491 non-null    object
 2   description   405 non-null    object
 3   published_at  491 non-null    object
 4   viewCount     491 non-null    int64
 5   likeCount     491 non-null    int64
 6   commentCount  491 non-null    int64
 7   duration      491 non-null    int64
dtypes: int64(4), object(4)
memory usage: 30.8+ KB

In [6]:
df.describe()

          viewCount     likeCount  commentCount      duration
count  4.910000e+02    491.000000    491.000000    491.000000
mean   4.669661e+04   1785.690428    116.437882    819.087576
std    1.308113e+05   4487.456712    171.425326   1387.158621
min    8.930000e+02     40.000000      1.000000     11.000000
25%    6.108000e+03    362.500000     19.000000     59.000000
50%    1.214900e+04    682.000000     67.000000    552.000000
75%    3.163700e+04   1380.000000    146.000000    922.000000
max    1.785057e+06  72330.000000   2035.000000  19241.000000